# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-jBGV1al6tYyWAT79TzQX6KFxHAtcPNQ

Importing packages
"""

import pandas as pd
from sklearn.compose import make_column_selector as selector
import numpy as np
from sklearn.model_selection import train_test_split

"""# Reading data and setting aside 10%"""

df = pd.read_excel("Dropout_Data.xlsx", sheet_name="Original Data")

"""Checking columns' data types"""

print(df.dtypes)

"""Adding an ID for reproducible sampling (starting from 1)"""

df["StudentID"] = df.index + 1

"""Setting aside 10% of the data for testing the models at the very end"""

from sklearn.model_selection import train_test_split

df, df_holdout = train_test_split(df,test_size=0.10,stratify=df["Target"],random_state=3)

len(df)

len(df_holdout)

"""# Data cleaning and preprocessing

Selecting variables we will use

Target

Independent variables
- Previous qualification (grade)
- Mother's qualification
- Father's qualification
- Debtor
- Tuition fees up to date
- Gender
- Scholarship holder
- International
- Inflation rate
- GDP
"""

cols_to_keep = [
    "Target",
    "Previous qualification (grade)",
    "Mother's qualification",
    "Father's qualification",
    "Debtor",
    "Tuition fees up to date",
    "Gender",
    "Scholarship holder",
    "International",
    "Inflation rate",
    "GDP"
]

df = df[cols_to_keep]

"""Checking missing values"""

missing_values = df.isnull().sum()
print(missing_values)

"""There are none

Setting the target variable as categorical, removing students in the "Enrolled" category and encoding the target so that Dropout=0 and Graduated=1
"""

df = df[df["Target"] != "Enrolled"].copy()
df["Target"] = df["Target"].astype("category").cat.codes
df['Target'].unique()

"""Recoding mother's and father's education levels into 5 categories:

- unknown (0),
- low/no education (1),
- basic education (2: high-school levels),
- higher education (3: trade school and bachelor’s levels),
- high-level education (4: master’s, doctorate, and above levels)
"""

qualification_map = {
    # 0 – Unknown
    34: 0,

    # 1: Low/no education
    35: 1,  # Can't read or write
    36: 1,  # Can read without 4th year

    # 2: Basic education (1st–3rd cycles, secondary, complementary, commerce, etc.)
    1: 2,   # Secondary Education - 12th Year
    9: 2,   # 12th Year - Not Completed
    10: 2,  # 11th Year - Not Completed
    11: 2,  # 7th Year (Old)
    12: 2,  # Other - 11th Year
    13: 2,  # 2nd year complementary high school course (father)
    14: 2,  # 10th Year
    18: 2,  # General commerce course
    19: 2,  # Basic Education 3rd Cycle
    20: 2,  # Complementary High School Course (father)
    22: 2,  # Technical-professional course
    25: 2,  # Complementary High School Course - not concluded (father)
    26: 2,  # 7th year of schooling
    27: 2,  # 2nd cycle of general high school
    29: 2,  # 9th Year - Not Completed
    30: 2,  # 8th year
    31: 2,  # General Course of Administration and Commerce (father)
    33: 2,  # Supplementary Accounting and Administration (father)
    37: 2,  # Basic education 1st cycle
    38: 2,  # Basic education 2nd cycle

    # 3: Higher education (non-master)
    2: 3,   # Higher Education - Bachelor's
    3: 3,   # Higher Education - Degree
    6: 3,   # Frequency of Higher Education
    39: 3,  # Technological specialization course
    40: 3,  # Higher education - degree (1st cycle)
    41: 3,  # Specialized higher studies course
    42: 3,  # Professional higher technical course

    # 4: High-level higher education
    4: 4,   # Higher Education - Master's
    5: 4,   # Higher Education - Doctorate
    43: 4,  # Higher Education - Master (2nd cycle)
    44: 4   # Higher Education - Doctorate (3rd cycle)
}

df["Mother's qualification"] = df["Mother's qualification"].map(qualification_map)
df["Father's qualification"] = df["Father's qualification"].map(qualification_map)

df["Mother's qualification"].value_counts(normalize=True).sort_index()

df["Father's qualification"].value_counts(normalize=True).sort_index()

print(df.dtypes)

"""Converting categorical variables (to avoid treating them as numeric!)"""

# Unordered categorical
categoricals = [
    "Debtor",
    "Tuition fees up to date",
    "Gender",
    "Scholarship holder",
    "International",
    "Target"
]

df[categoricals] = df[categoricals].astype("category")

# Ordered categorical for parents' education
qual_order = [0,1,2,3,4]
qualification_type = pd.CategoricalDtype(categories=qual_order, ordered=True)

df["Mother's qualification"] = df["Mother's qualification"].astype(qualification_type)
df["Father's qualification"] = df["Father's qualification"].astype(qualification_type)

"""Separating features and target variable"""

y = df["Target"]
X = df.drop(columns=["Target"])

y.head()

X.head()

#######################################################################################################################
#######################################################################################################################

"""# EDA, Visualizations - Balázs

Descriptive statistics table for all variables
"""

feature_cols = [
    "Previous qualification (grade)",
    "Mother's qualification",
    "Father's qualification",
    "Debtor",
    "Tuition fees up to date",
    "Gender",
    "Scholarship holder",
    "International",
    "Inflation rate",
    "GDP"
]

target_col = "Target"

df_sub = df[feature_cols + [target_col]]


desc = df_sub.describe(include='all').T

desc["dtype"] = df_sub.dtypes.astype(str)
desc["nunique"] = df_sub.nunique()
desc["missing_count"] = df_sub.isna().sum()

first_cols = ["dtype", "nunique", "missing_count"]
other_cols = [c for c in desc.columns if c not in first_cols]

summary = desc[first_cols + other_cols].copy()

num_cols = summary.select_dtypes(include="number").columns
summary[num_cols] = summary[num_cols].round(3)

summary

"""Separate descriptive statistics tables for the explanatory variables and for the outcome variable"""

feature_cols = [
    "Previous qualification (grade)",
    "Mother's qualification",
    "Father's qualification",
    "Debtor",
    "Tuition fees up to date",
    "Gender",
    "Scholarship holder",
    "International",
    "Inflation rate",
    "GDP"
]

if "Target" in df.columns:
    target_col = "Target"
else:

    target_candidates = [c for c in df.columns if c not in feature_cols]
    target_col = target_candidates[0]

# Descriptive statistics table for the explanatory variables

x = df[feature_cols]

desc_feat = x.describe(include='all').T

desc_feat["dtype"] = x.dtypes.astype(str)
desc_feat["nunique"] = x.nunique()
desc_feat["missing_count"] = x.isna().sum()

first_cols = ["dtype", "nunique", "missing_count"]
other_cols = [c for c in desc_feat.columns if c not in first_cols]

summary_features = desc_feat[first_cols + other_cols].copy()
num_cols = summary_features.select_dtypes(include="number").columns
summary_features[num_cols] = summary_features[num_cols].round(3)

# Descriptive statistics table for the outcome variables
y = df[target_col]

desc_tgt = y.describe(include='all').to_frame().T

desc_tgt["dtype"] = y.dtype
desc_tgt["nunique"] = y.nunique()
desc_tgt["missing_count"] = y.isna().sum()

first_cols_t = ["dtype", "nunique", "missing_count"]
other_cols_t = [c for c in desc_tgt.columns if c not in first_cols_t]

summary_target = desc_tgt[first_cols_t + other_cols_t].copy()
num_cols_t = summary_target.select_dtypes(include="number").columns
summary_target[num_cols_t] = summary_target[num_cols_t].round(3)


summary_features

summary_target

"""Dropout vs Graduate proportion figure"""

import matplotlib.pyplot as plt

#Dropout vs Graduate proportion
target_col = "Target"

df_target = df.copy()
if df_target[target_col].dtype == "object":
    df_target = df_target[df_target[target_col] != "Enrolled"]

# Compute class proportions in percentages
target_ratio = df_target[target_col].value_counts(normalize=True) * 100

# Plot
plt.figure()
target_ratio.plot(kind="bar")
plt.title("Dropout vs Graduate proportion (Target)")
plt.ylabel("Percentage (%)")
plt.xlabel("Target class")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""Histogram of previous qualification"""

# Previous qualification (grade)
plt.figure()
df["Previous qualification (grade)"].dropna().hist(bins=30)
plt.title("Histogram of Previous qualification (grade)")
plt.xlabel("Previous qualification (grade)")
plt.ylabel("Frequency")
plt.tight_layout()
plt.show()

"""Boxplot of Inflation rate and GDP"""

#Inflation rate and GDP
plt.figure()

plt.boxplot(
    [df["Inflation rate"].dropna(), df["GDP"].dropna()],
    labels=["Inflation rate", "GDP"]
)
plt.title("Boxplot of Inflation rate and GDP")
plt.ylabel("Value")
plt.tight_layout()
plt.show()

"""Distribution of parental qualification levels"""

#Parental qualification levels
mother_prop = df["Mother's qualification"].value_counts(normalize=True).sort_index()
father_prop = df["Father's qualification"].value_counts(normalize=True).sort_index()

# Combine into one DataFrame for plotting
qual_prop = pd.DataFrame({
    "Mother": mother_prop,
    "Father": father_prop
})

# Ensure all levels 0–4 appear in the index (even if one level is missing)
qual_prop = qual_prop.reindex([0, 1, 2, 3, 4])

# Plot grouped bar chart of proportions
ax = qual_prop.plot(kind="bar")
ax.set_title("Distribution of parental qualification levels")
ax.set_xlabel("Qualification level (0–4)")
ax.set_ylabel("Proportion")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

"""Distribution of other dummy variables"""

# List of dummy explanatory variables
dummy_cols = ["International",
              "Scholarship holder",
              "Gender",
              "Tuition fees up to date",
              "Debtor"]

for col in dummy_cols:
    plt.figure()
    # Keep only valid 0/1 values and drop missing
    data = df[col].dropna()
    data = data[data.isin([0, 1])]

    # Histogram with two adjacent bins: one for 0, one for 1
    plt.hist(data, bins=[-0.5, 0.5, 1.5])
    plt.xticks([0, 1], ["0", "1"])
    plt.title(f"Histogram of {col}")
    plt.xlabel(col)
    plt.ylabel("Count")
    plt.tight_layout()
    plt.show()

"""# Preprocessing for modeling"""

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (confusion_matrix,accuracy_score,precision_score,recall_score,roc_auc_score)
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.model_selection import GridSearchCV

"""Further preprocessing/ feature engineering: One-hot encoding the categorical variables and scaling the numeric ones"""

numeric = ["Previous qualification (grade)","Inflation rate","GDP"]
categorical = ["Mother's qualification", "Father's qualification","Debtor","Tuition fees up to date","Gender","Scholarship holder","International"]

preprocess = ColumnTransformer(
    transformers=
     [("num", StandardScaler(), numeric),
     ("cat", OneHotEncoder(drop="first", handle_unknown="ignore"), categorical),]
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=3)

# VSCODEBAN A MODEL.PY-BAN AZ EVALUTE.PY-BÓL IMPORTÁLOM CV-KÉNT, DE AZ EVALUATE MÉG NINCS KÉSZ
# Stratified 5-fold CV: we will use this for evaluating the models

"""# Logistic regression: baseline model

With no parameter tuning. Using default parameters for our baseline model.
"""

log_reg = LogisticRegression(max_iter=100, random_state=42)

baseline_model = make_pipeline(
    preprocess,
    log_reg
)

baseline_model.fit(X,y)

# Train/test split
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

print(X_train.shape, X_test.shape)

"""Visualization

"""

#Prep
from sklearn.metrics import (
    ConfusionMatrixDisplay,
    confusion_matrix,
    RocCurveDisplay,
    roc_auc_score,
)

from matplotlib.colors import ListedColormap

baseline_model.fit(X_train, y_train)

y_proba = baseline_model.predict_proba(X_test)[:, 1]
y_pred  = baseline_model.predict(X_test)

# Confusion matrix
labels = [0, 1]
cm = confusion_matrix(y_test, y_pred, labels=labels)


n = cm.shape[0]
correct_mask = np.eye(n)
cmap = ListedColormap(['#E53935', '#43A047'])

fig, ax = plt.subplots(figsize=(5, 4))
ax.imshow(correct_mask, cmap=cmap, vmin=0, vmax=1)


cm_norm = cm / cm.sum(axis=1, keepdims=True)
for (i, j), val in np.ndenumerate(cm):
    txt = f"{val}\n({cm_norm[i, j]:.2f})"
    ax.text(j, i, txt, ha="center", va="center", color="white", fontsize=12, fontweight="bold")

ax.set_xticks(range(n)); ax.set_yticks(range(n))
ax.set_xticklabels([f"Pred {l}" for l in labels])
ax.set_yticklabels([f"True {l}" for l in labels])
ax.set_title("Confusion matrix")
ax.set_xlim(-0.5, n-0.5); ax.set_ylim(n-0.5, -0.5)
plt.tight_layout(); plt.show()

# ROC curve + AUC
auc = roc_auc_score(y_test, y_proba)
fig, ax = plt.subplots()
RocCurveDisplay.from_predictions(y_test, y_proba, ax=ax)
ax.set_title(f"ROC curve (AUC = {auc:.3f})")
plt.show()

#probability vs. logit/decision function plot
z = baseline_model.decision_function(X_test)
p = baseline_model.predict_proba(X_test)[:, 1]

fig, ax = plt.subplots(figsize=(7,4))

mask1 = (y_test == 1)
mask0 = ~mask1
ax.scatter(z[mask0], p[mask0], s=12, alpha=0.6, label="True 0")
ax.scatter(z[mask1], p[mask1], s=12, alpha=0.6, label="True 1")

zz = np.linspace(z.min()-1, z.max()+1, 400)
ax.plot(zz, 1/(1+np.exp(-zz)), linewidth=2, label="σ(z)")

ax.axhline(0.5, linestyle="--", linewidth=1)
ax.axvline(0.0, linestyle="--", linewidth=1)

ax.set_xlabel("Linear score  z = decision_function(x)")
ax.set_ylabel("Predicted probability  σ(z)")
ax.set_title("Logistic link on model outputs")
ax.legend()
ax.grid(True, alpha=0.3)
plt.tight_layout(); plt.show()

"""# Lasso model

To "drop" non-significant variables.
"""

lasso_model = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    max_iter=100,
    random_state=3
)

lasso = make_pipeline(
    preprocess,
    lasso_model
)

lasso.fit(X,y)

"""Visualization

"""

def get_feature_names_from_ct(ct):
    names = []
    for name, transformer, cols in ct.transformers_:
        if name == 'remainder':
            continue
        if hasattr(transformer, "get_feature_names_out"):
            feats = transformer.get_feature_names_out(cols)
        else:
            feats = np.array(cols)
        names.extend(feats)
    return np.array(names)

ct   = lasso.named_steps[next(iter(lasso.named_steps))]
logr = lasso.named_steps['logisticregression']
feat_names = get_feature_names_from_ct(ct)
coefs = logr.coef_.ravel()

"""Non-zero coefficients"""

nz = np.flatnonzero(coefs)
k  = min(25, len(nz))
idx = nz[np.argsort(np.abs(coefs[nz]))[::-1][:k]]

fig, ax = plt.subplots(figsize=(8, max(4, 0.35*k)))
colors = np.where(coefs[idx] >= 0, "#2E7D32", "#C62828")
ax.barh(range(len(idx)), coefs[idx], color=colors)
ax.set_yticks(range(len(idx)))
ax.set_yticklabels(feat_names[idx])
ax.invert_yaxis()
ax.set_title("Top L1-logit coefficients (survivors)")
ax.set_xlabel("Coefficient value (→ class 1)")
plt.tight_layout(); plt.show()

"""Non-zero coefficients in different order"""

nz = np.flatnonzero(coefs)
k  = min(25, len(nz))

sel = nz[np.argsort(np.abs(coefs[nz]))[::-1][:k]]

# new order
idx = sel[np.argsort(coefs[sel])]

fig, ax = plt.subplots(figsize=(8, max(4, 0.35*len(idx))))
colors = np.where(coefs[idx] >= 0, "#2E7D32", "#C62828")
ax.barh(np.arange(len(idx)), coefs[idx], color=colors)

ax.set_yticks(np.arange(len(idx)))
ax.set_yticklabels(feat_names[idx])

ax.axvline(0, color='k', lw=1)
ax.set_title("Top L1-logit coefficients (most negative bottom → most positive top)")
ax.set_xlabel("Coefficient value (→ class 1)")
plt.tight_layout(); plt.show()

"""Sparsity path"""

from sklearn.linear_model import LogisticRegression

Cs = np.logspace(-3, 1, 15)   # smaller C → stronger penalty
nonzeros = []
for C in Cs:
    model = make_pipeline(
        preprocess,
        LogisticRegression(penalty='l1', solver='liblinear', C=C, max_iter=100, random_state=3)
    )
    model.fit(X_train, y_train)
    nz_cnt = np.count_nonzero(model.named_steps['logisticregression'].coef_)
    nonzeros.append(nz_cnt)

plt.figure(figsize=(6,4))
plt.plot(Cs, nonzeros, marker='o')
plt.xscale('log')
plt.gca().invert_xaxis()   #stronger penalty on the left
plt.xlabel("C (smaller → stronger L1)")
plt.ylabel("Number of non-zero coefficients")
plt.title("Sparsity path (L1)")
plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

"""Coefficient path"""

baseC = 1.0
probe = make_pipeline(
    preprocess,
    LogisticRegression(penalty='l1', solver='liblinear', C=baseC, max_iter=100, random_state=3)
).fit(X_train, y_train)
base_coef = probe.named_steps['logisticregression'].coef_.ravel()
top_idx = np.argsort(np.abs(base_coef))[-13:]  # top 13 (we can change that)

paths = {i: [] for i in top_idx}
for C in Cs:
    m = make_pipeline(
        preprocess,
        LogisticRegression(penalty='l1', solver='liblinear', C=C, max_iter=100, random_state=3)
    ).fit(X_train, y_train)
    c = m.named_steps['logisticregression'].coef_.ravel()
    for i in top_idx:
        paths[i].append(c[i])

plt.figure(figsize=(7,4))
for i, vals in paths.items():
    plt.plot(Cs, vals, label=feat_names[i])
plt.xscale('log'); plt.gca().invert_xaxis()
plt.axhline(0, color='k', lw=1)
plt.xlabel("C (smaller → stronger L1)")
plt.ylabel("Coefficient")
plt.title("Coefficient paths (selected features)")
plt.legend(ncol=2, fontsize=8)
plt.tight_layout(); plt.show()

"""ROC curve + AUC"""

from sklearn.metrics import RocCurveDisplay, roc_auc_score

# Lasso  AUC
y_proba_l1 = lasso.predict_proba(X_test)[:, 1]
auc_l1 = roc_auc_score(y_test, y_proba_l1)

# ROC curve
fig, ax = plt.subplots(figsize=(6,4))
RocCurveDisplay.from_predictions(
    y_test, y_proba_l1, ax=ax, name=f"L1 (AUC={auc_l1:.3f})"
)
ax.plot([0,1], [0,1], '--', lw=1, color='gray')  # referencia
ax.set_title("ROC curve — L1 (Lasso)")
plt.tight_layout(); plt.show()

"""ROC curve + AUC VS Baseline model"""

# lasso
y_proba_l1 = lasso.predict_proba(X_test)[:,1]
auc_l1 = roc_auc_score(y_test, y_proba_l1)

# baseline
y_proba_base = baseline_model.predict_proba(X_test)[:,1]
auc_base = roc_auc_score(y_test, y_proba_base)

fig, ax = plt.subplots(figsize=(6,4))
RocCurveDisplay.from_predictions(y_test, y_proba_base, ax=ax, name=f"Baseline (AUC={auc_base:.3f})")
RocCurveDisplay.from_predictions(y_test, y_proba_l1, ax=ax, name=f"L1 (AUC={auc_l1:.3f})")
ax.plot([0,1],[0,1],'--',lw=1,color='gray')
ax.set_title("ROC curves: Baseline vs L1")
plt.tight_layout(); plt.show()

"""# K-NN

Non-parametric. Model parameters to tune: n_neighbors, weights using Grid Search.
"""

knn_model = KNeighborsClassifier(weights="distance",metric="cosine")

knn = make_pipeline(
    preprocess,
    knn_model
)


param_grid_knn = {
  "kneighborsclassifier__n_neighbors": [3, 5, 10, 15, 25]}


grid_knn = GridSearchCV(
    estimator=knn,
    param_grid=param_grid_knn,
    scoring="accuracy",
    cv=cv,
    n_jobs=-1
)

grid_knn.fit(X,y)

"""Visualization

Validation curve
"""

cvres = grid_knn.cv_results_
ks = cvres["param_kneighborsclassifier__n_neighbors"].data.astype(int)
mean = cvres["mean_test_score"]
std  = cvres["std_test_score"]

order = np.argsort(ks)
ks, mean, std = ks[order], mean[order], std[order]

plt.figure(figsize=(6,4))
plt.plot(ks, mean, marker="o")
plt.fill_between(ks, mean-std, mean+std, alpha=0.2)
plt.xlabel("k (n_neighbors)")
plt.ylabel("CV accuracy")
plt.title("Validation curve (KNN)")
plt.grid(True, alpha=0.3); plt.tight_layout(); plt.show()

"""ROC curve + AUC"""

y_proba = best_knn.predict_proba(X_test)[:,1]
auc = roc_auc_score(y_test, y_proba)

fig, ax = plt.subplots(figsize=(6,4))
RocCurveDisplay.from_predictions(y_test, y_proba, ax=ax, name=f"KNN (AUC={auc:.3f})")
ax.plot([0,1],[0,1],'--',lw=1,color='gray')
ax.set_title("ROC curve — best KNN")
plt.tight_layout(); plt.show()


grid_knn.best_params_ #best K = 15

"""ROC for Baseline, L1 (Lasso), and best KNN on the same figure"""

best_knn = grid_knn.best_estimator_

p_base = baseline_model.predict_proba(X_test)[:, 1]
p_l1   = lasso.predict_proba(X_test)[:, 1]
p_knn  = best_knn.predict_proba(X_test)[:, 1]

# AUCs
auc_base = roc_auc_score(y_test, p_base)
auc_l1   = roc_auc_score(y_test, p_l1)
auc_knn  = roc_auc_score(y_test, p_knn)

# Plot
fig, ax = plt.subplots(figsize=(7,5))
RocCurveDisplay.from_predictions(y_test, p_base, ax=ax, name=f"Baseline (AUC={auc_base:.3f})")
RocCurveDisplay.from_predictions(y_test, p_l1,   ax=ax, name=f"L1 (AUC={auc_l1:.3f})")
RocCurveDisplay.from_predictions(y_test, p_knn,  ax=ax, name=f"KNN (AUC={auc_knn:.3f})")

# Chance line
ax.plot([0,1], [0,1], '--', color='gray', lw=1)

ax.set_title("ROC curves — Baseline vs L1 vs KNN")
ax.legend(loc="lower right")

plt.tight_layout(); plt.show()

"""# Decision tree

Another non-parametric model. Tune max_depth and min_samples_leaf
"""

tree_model = DecisionTreeClassifier(criterion="entropy")

tree = make_pipeline(
    preprocess,
    tree_model
    )

param_grid_tree = {
    'model__max_depth': [2, 3, 5, 10],
    'model__min_samples_leaf': [1, 5, 10, 25]}

grid_tree = GridSearchCV(
    estimator = tree,
    param_grid = param_grid_tree,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1)

grid_tree.fit(X,y)

"""#Evaluation, comparison, picking the best model

Evaluating the 4 tuned models, based on AUC, accuracy, precision (Among predicted Graduates (1), how many were truly Graduates?) and recall (Among real Graduates (1), how many did we correctly predict?)

AUC
"""

auc_scores = cross_val_score(
    baseline_model,
    X,
    y,
    cv=cv,
    scoring="roc_auc"
)
print(f"Baseline Logistic Regression AUC (CV mean and std): "f"{auc_scores.mean():.3f} ± {auc_scores.std():.3f}")

# FUNCTION version

def evaluate_auc(model):
    """
    Computes cross-validated AUC for model.
    """
    auc_scores = cross_val_score(
        estimator=model,
        X=X,
        y=y,
        cv=cv,
        scoring="roc_auc"
    )

    print(f"AUC (CV mean ± std): {auc_scores.mean():.3f} ± {auc_scores.std():.3f}")
    return auc_scores

"""Accuracy"""

acc_scores = cross_val_score(
    baseline_model,
    X,
    y,
    cv=cv,
    scoring="accuracy"
)
print(f"Baseline Logistic Regression Accuracy (CV mean and std): "f"{acc_scores.mean():.3f} ± {acc_scores.std():.3f}")

# FUNCTION version

def evaluate_accuracy(model):
    """
    Computes cross-validated ACCURACY for model.
    """
    acc_scores = cross_val_score(
        estimator=model,
        X=X,
        y=y,
        cv=cv,
        scoring="accuracy"
    )

    print(f"Accuracy (CV mean ± std): {acc_scores.mean():.3f} ± {acc_scores.std():.3f}")
    return acc_scores

"""Precision"""

precision_scores = cross_val_score(
    baseline_model, # itt baseline_model?
    X,
    y,
    cv=cv,
    scoring="precision"
)
print(f"Baseline Logistic Regression Precision (CV mean and std): "f"{precision_scores.mean():.3f} ± {precision_scores.std():.3f}")

# FUNCTION version

def evaluate_precision(model):
    """
    Computes cross-validated PRECISION for model.
    """
    precision_scores = cross_val_score(
        estimator=model,
        X=X,
        y=y,
        cv=cv,
        scoring="precision"
    )

    print(f"Precision (CV mean ± std): {precision_scores.mean():.3f} ± {precision_scores.std():.3f}")
    return precision_scores

"""Recall"""

recall_scores = cross_val_score(
    baseline_model, # itt baseline_model?
    X,
    y,
    cv=cv,
    scoring="recall"
)
print(f"Baseline Logistic Regression Recall (CV mean and std): "f"{recall_scores.mean():.3f} ± {recall_scores.std():.3f}")

# FUNCTION version

def evaluate_recall(model, X, y, cv):
    """
    Computes cross-validated RECALL for model.
    """
    recall_scores = cross_val_score(
        estimator=model,
        X=X,
        y=y,
        cv=cv,
        scoring="recall"
    )

    print(f"Recall (CV mean ± std): {recall_scores.mean():.3f} ± {recall_scores.std():.3f}")
    return recall_scores

"""Visualizations: confusion matrices, ROC curves

# Checking multicollinearity between features

I. Correlation matrix + heatmap
"""

import seaborn as sns
import matplotlib.pyplot as plt

corr = df.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()

# Possible concerns:
# 0.63 --> Father's qualifications x Mother's qualification (moderate multicollinearity)
# -0.43 --> Tuition fees up to date x Debtor (should not be a problem)

# FUNCTION version

def multicollinearity_corr_heatmap(df)

  """
  Computes the correlation matrix for all numeric columns
  in the DataFrame and plots a correlation heatmap.
  """
  corr = df.corr()

  plt.figure(figsize=(12, 8))
  sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")
  plt.title("Correlation Heatmap")
  plt.show()

"""II. Variance Inlfation Factor (VIF): It can **only work with continuous numeric variables**!!!

*   1-5: no serious multicollinearity
*   5-10: moderate multicollinearity
*   10+: strong multicollinearity



"""

from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# FUNCTION version

def multicollinearity_vif(df)

  """
  Computes the correlation matrix for all numeric columns
  in the DataFrame and plots a correlation heatmap.
  """
  X = df.select_dtypes(include=["float64", "int64", "int8"]).dropna()

  X_const = sm.add_constant(X)

  vif_df = pd.DataFrame()
  vif_df["feature"] = X.columns
  vif_df["VIF"] = [variance_inflation_factor(X_const.values, i+1)
                  for i in range(len(X.columns))]

  print(vif_df)
  return vif_df

"""III. Removing reduntant variables, re-running models again with the adusted set of features"""

#code here

"""# Trying our models on the 10% holdout dataset"""

#code here